version: '3.5'

services:
  postgres:
    image: postgis/postgis:14-master
    networks:
      - internal
    ports:
      - 5644:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registras
      TZ: 'Etc/GMT'
      PGTZ: 'Etc/GMT'

  redis:
    image: redis:latest
    networks:
      - internal
    ports:
      - 5691:6379

networks:
  internal:

volumes:
  data:
