name: Deploy to Production
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-production:
    name: Deploy production
    uses: Nacionaline-sporto-agentura/reusable-workflows/.github/workflows/sporto-registras-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Production
      docker-image: ghcr.io/Nacionaline-sporto-agentura/sporto-registras-api
