name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    name: Deploy staging
    uses: Nacionaline-sporto-agentura/reusable-workflows/.github/workflows/sporto-registras-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Staging
      docker-image: ghcr.io/Nacionaline-sporto-agentura/sporto-registras-api
